### ISSUE TITLE
Add svelte

### ISSUE THREAD

**Issue by Suya1671** [Ender-Wiggin2019/VTuber-Logos-Collection#12]
Heres a couple I found online:
- https://x.com/mkpoli/status/1781931713939288337
- https://x.com/styxpilled/status/1781565832251719868

**Comment by Ender-Wiggin2019** [comment]
Sure, I will add it after one of the main repo is recovered

**Comment by Ender-Wiggin2019** [comment]
Hi Suyashtnt, I have added the one in first link. I cannot find a png in the second link. If you want you can create a PR for it.
