### ISSUE TITLE
new logo request, original 

### ISSUE THREAD

**Issue by steb-git** [Ender-Wiggin2019/VTuber-Logos-Collection#14]
Hello, I'm a designer and I've come across your site which indexes vtuber-style variants of popular logos.

I happen to have made some, and I figured that it would be nice to have them stored here for safekeeping, but also to showcase them as well.

The logo is for my school where I am currently taking my studies, and I decided to make one for our arts and design organization out of ennui.

![20240504_152743.jpg](https://github.com/Ender-Wiggin2019/VTuber-Logos-Collection/assets/37263820/b9397a89-d827-408a-98d1-0c92625de59c)
>  Design guideline

![20240504_004458.png](https://github.com/Ender-Wiggin2019/VTuber-Logos-Collection/assets/37263820/b187a6b6-a47e-45a7-bf0b-6582a17e484c)
> Original variant

![20240504_012051.png](https://github.com/Ender-Wiggin2019/VTuber-Logos-Collection/assets/37263820/d658e638-2150-449f-bc29-ff051c829ff5)
> Variant with tagline

If you would wish to take a look at them and download them with better quality, [you can check this Google Drive folder
](https://drive.google.com/drive/folders/1p-7VxOXa5eK0hydJkXYiHORQa6Bu6N9h)

Best regards,
@the_steb

**Comment by Ender-Wiggin2019** [comment]
Hi steb, I like your work. You can create a new file among [here](https://github.com/Ender-Wiggin2019/VTuber-Logos-Collection/tree/main/src/data/DownloadedLogos) if you know how to develop this repo.

**Comment by steb-git** [comment]
Hello, thanks for the swift reply! I will open a PR once the logo has been added.

Thank you!
