### ISSUE TITLE
Dont know how to add more

### ISSUE THREAD

**Issue by murimurikyu** [Ender-Wiggin2019/VTuber-Logos-Collection#16]
I'm new to git hub and dont know much about codding , i made my self a bit of it , but dont know how to upload them
https://drive.google.com/drive/mobile/folders/13HGThol9SmYyBJ9D3D7-Lmr1P_drqNHU?usp=drive_link&fbclid=IwZXh0bgNhZW0CMTEAAR0MbGSbUxYCQV7MEDDlgD09HnAzI7eZNq5NP1dT0NbZl51sTdErqcTFFos_aem_AbqnduE7ehovNR63pejJBMjJK2RpRTcnSbPWOBGqCZ4kj6xtwVKidR17aTa6sELCiora2nZ0E0Xpx9n6f_73ABtD

**Comment by Ender-Wiggin2019** [comment]
Hi murimurikyu, I like your work, such as p***hub lol. I will write a guide for uploading images after a while.
Btw, temporarily this repo cannot be updated because one of the main source has some change. I will do some work after that repo is recovered.

**Comment by murimurikyu** [comment]
Thanks
