### ISSUE TITLE
We need a cute logo for Visual Studio

### ISSUE THREAD

**Issue by BlameTwo** [Ender-Wiggin2019/VTuber-Logos-Collection#3]
As the title suggests

**Comment by swety2003** [comment]
Here: [>ProgrammingVTuberLogos-VisualStudio](https://github.com/hvpexe/ProgrammingVTuberLogos-VisualStudio)

**Comment by Ender-Wiggin2019** [comment]
Hi BlameTwo, there're 2 steps for this issue:

1. seek any existing logos on Internet. There're still many VTuber-style logos that this repo doesn't contains. If you find them, you can directly use it, or that would be super great if you make a PR for this collection repo.
2. If you can't find any, you can create an issue [here](https://github.com/SAWARATSUKI/ServiceLogos/issues) to ask cute logo master SAWARATSUKI to do you a favor.

This repo aims at collecting existing logos from artists. So it's okay to create a issue, but all I can do is finding the logo and add it to the website.

**Comment by Ender-Wiggin2019** [comment]
> Here: [>ProgrammingVTuberLogos-VisualStudio](https://github.com/hvpexe/ProgrammingVTuberLogos-VisualStudio)

Thanks, I will add it sometime later
